name: Java CI

on:
  push:
    branches: [ main ]
    paths:
      - 'java/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'java/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd java
        mvn -B package --file pom.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SecureQR-Java
        path: java/target/secure-qr-*.jar